spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # jpa설정
  jpa:
    hibernate:
      ddl-auto: create

    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.SQL: trace