spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080

service:
  invitation:
    secret: my-secret